#!/bin/sh
set -e

if command -v systemctl >/dev/null 2>&1; then
    systemctl daemon-reload >/dev/null 2>&1 || true
fi

if [ "$1" = purge ]; then
    rm -f /etc/default/linuwu-profile-helper
fi

exit 0
